\ Conway's game of life.

0 VALUE GR-MODE
0 VALUE BOARD-WIDTH
0 VALUE BOARD-HEIGHT
[DEFINED] GRAPHICS-PARAMS [IF]
  GRAPHICS-PARAMS 2DROP DUP [IF]
    255 > [IF]
      \ Have high-res graphics plot 4x4 blocks
      2 TO GR-MODE GRAPHICS-PARAMS DROP 4 / TO BOARD-HEIGHT 4 / TO BOARD-WIDTH
    [ELSE]
      \ Have low-res graphics plot single dots
      1 TO GR-MODE GRAPHICS-PARAMS DROP TO BOARD-HEIGHT TO BOARD-WIDTH
    [THEN]
    GRAPHICS-MODE
  [ELSE]
    DROP
  [THEN]
[THEN]
GR-MODE 0= [IF]
  \ Have no graphics, plot '*' characters
  SCREEN-SIZE 2 - TO BOARD-HEIGHT TO BOARD-WIDTH
[THEN]

SCREEN-SIZE 2 - CONSTANT BOT-ROW DROP
\ GR-MODE . BOARD-WIDTH . BOARD-HEIGHT . BOT-ROW .

\ Margin at each side of the board around the visible area.
\ There will be an additional margin on each side where pixels are never
\ drawm
5 CONSTANT MARGIN

BOARD-WIDTH MARGIN 2* 2 + + CONSTANT TOTAL-ROW-SIZE
BOARD-HEIGHT MARGIN 2* 2 + + CONSTANT TOTAL-ROWS

VARIABLE SEED 
CURRENT-TIME DROP SEED !

: RAND ( n1 --- n2)
\G A simple random generator return a number in range 0..n2-1
  SEED @ 3533 * 433 + DUP SEED ! UM* NIP ;

CREATE BOARD1 TOTAL-ROW-SIZE TOTAL-ROWS * ALLOT
CREATE BOARD2 TOTAL-ROW-SIZE TOTAL-ROWS * ALLOT
BOARD1 TOTAl-ROW-SIZE TOTAl-ROWS * ERASE
BOARD2 TOTAl-ROW-SIZE TOTAl-ROWS * ERASE

BOARD1 VALUE OLD-BOARD
BOARD2 VALUE NEW-BOARD

GR-MODE 0= [IF]
: DRAW-BOARD
  0 0 AT-XY
  MARGIN 1+ BOARD-HEIGHT BOUNDS DO
    MARGIN 1+ BOARD-WIDTH BOUNDS DO
      OLD-BOARD J TOTAL-ROW-SIZE * + I + C@ IF '*' ELSE BL THEN EMIT 
    LOOP
  LOOP ;
[ELSE]
GR-MODE 1 = [IF]
: DRAW-BOARD
  CLG
  BOARD-HEIGHT 0 DO
    BOARD-WIDTH 0 DO
      OLD-BOARD J MARGIN + 1+ TOTAL-ROW-SIZE * + I MARGIN + 1+ + C@
      IF I J PLOTDOT THEN
    LOOP
  LOOP REDRAW ;

[ELSE]
CREATE PATTERN $F0 C, $F0 C, $F0 C, $F0 C,
: DRAW-BOARD
  CLG
  BOARD-HEIGHT 0 DO
    BOARD-WIDTH 0 DO
      OLD-BOARD J MARGIN + 1+ TOTAL-ROW-SIZE * + I MARGIN + 1+ + C@
      IF PATTERN I 4 * J 4 * 4 4 PUT-BITMAP-MONO THEN
    LOOP
  LOOP REDRAW ;

[THEN]
[THEN]

: FILL-BOARD
  OLD-BOARD TOTAl-ROW-SIZE TOTAl-ROWS * ERASE
  MARGIN 1+ BOARD-HEIGHT BOUNDS DO
    MARGIN 1+ BOARD-WIDTH BOUNDS DO
     4 RAND 0= IF 1  OLD-BOARD J TOTAL-ROW-SIZE * + I + C! THEN
    LOOP
  LOOP ;

\ FILL-BOARD DRAW-BOARD

0 VALUE GENERATION

: SWAP-BOARDS OLD-BOARD NEW-BOARD TO OLD-BOARD TO NEW-BOARD ;

: UPDATE-BOARD
  TOTAL-ROWS 2 - 1 DO
    TOTAl-ROW-SIZE 2 - 1 DO
      OLD-BOARD J TOTAL-ROW-SIZE * + I +
      DUP 1- C@
      OVER 1+ C@ +
      OVER TOTAL-ROW-SIZE - 1- C@ +
      OVER TOTAL-ROW-SIZE - C@ + 
      OVER TOTAL-ROW-SIZE - 1+ C@ +
      OVER TOTAL-ROW-SIZE + 1- C@ +
      OVER TOTAL-ROW-SIZE +  C@ +
      OVER TOTAL-ROW-SIZE + 1+ C@ +
      DUP 2 < IF
        2DROP 0
      ELSE
        DUP 2 = IF
	  DROP C@
	ELSE
	  3 = IF
	    DROP 1
	  ELSE
	    DROP 0
	  THEN
	THEN
      THEN
      NEW-BOARD J TOTAL-ROW-SIZE * + I + C!
    LOOP
  LOOP ;


: LIFE PAGE
  BEGIN
    0 TO GENERATION
    FILL-BOARD
    BEGIN 
      DRAW-BOARD
      0 BOT-ROW AT-XY ." Generation:" GENERATION 5 .R
      UPDATE-BOARD
      1 +TO GENERATION
      SWAP-BOARDS 250 MS 
      KEY? UNTIL
   KEY 27 = UNTIL ;

LIFE BYE

