/* Embeddable C-based FORTH interpreter.
   Copyright 2025 L.C. Benschop, Vught, The Netherlands.
   The program is released under the MIT license.
   here is NO WARRANTY.
*/


#define OP_NOOP              0x00
#define OP_CALL              0x01
#define OP_FBRANCH           0x02
#define OP_BBRANCH           0x03
#define OP_QFBRANCH          0x04
#define OP_QBBRANCH          0x05
#define OP_LIT8              0x06
#define OP_LIT8N             0x07
#define OP_LIT16             0x08
#define OP_LIT16N            0x09
#define OP_LIT24             0x0A
#define OP_LIT24N            0x0B
#define OP_LIT               0x0C
#define OP_FLIT              0x0D

#define OP_QDO               0x10
#define OP_DO                0x11
#define OP_LOOP              0x12
#define OP_PLUSLOOP          0x13
#define OP_LEAVE             0x14
#define OP_EXIT              0x15
#define OP_RTI               0x16
#define OP_RFROM             0x18
#define OP_TOR               0x19
#define OP_RFETCH            0x1A
#define OP_I                 0x1B
#define OP_IPRIME            0x1C
#define OP_J                 0x1D
#define OP_UNLOOP            0x1E

#define OP_DROP              0x20
#define OP_DUP               0x21
#define OP_SWAP              0x22
#define OP_OVER              0x23
#define OP_NIP               0x24
#define OP_TUCK              0x25
#define OP_ROT               0x26
#define OP_ROTN              0x27
#define OP_2DROP             0x28
#define OP_2DUP              0x29
#define OP_2SWAP             0x2A
#define OP_2OVER             0x2B
#define OP_PICK              0x2C
#define OP_ROLL              0x2D
#define OP_2TIMES            0x2E
#define OP_2SLASH            0x2F
#define OP_PLUS              0x30
#define OP_MINUS             0x31
#define OP_AND               0x32
#define OP_OR                0x33
#define OP_XOR               0x34
#define OP_NEGATE            0x35
#define OP_INVERT            0x36
#define OP_ABS               0x37
#define OP_TIMES             0x38
#define OP_UMTIMES           0x39
#define OP_MTIMES            0x3A
#define OP_USLASHMOD         0x3B
#define OP_FMSLASHMOD        0x3C
#define OP_SMSLASHREM        0x3D
#define OP_SLASH             0x3E
#define OP_MOD               0x3F
#define OP_DPLUS             0x40
#define OP_DNEGATE           0x41
#define OP_DMINUS            0x42
#define OP_DTIMES            0x43
#define OP_UDSLASHMOD        0x44
#define OP_DSLAHSMOD         0x45
#define OP_LSHIFT            0x46
#define OP_RSHIFT            0x47

#define OP_0EQ               0x48
#define OP_0NEQ              0x49
#define OP_0LESS             0x4A
#define OP_0GREATER          0x4B
#define OP_0LESSEQ           0x4C
#define OP_0GREATEREQ        0x4D
#define OP_D2TIMES           0x4E
#define OP_D2SLASH           0x4F
#define OP_EQ                0x50
#define OP_NEQ               0x51
#define OP_LESS              0x52
#define OP_GREATER           0x53
#define OP_LESSEQ            0x54
#define OP_GREATEREQ         0x55
#define OP_1PLUS             0x56
#define OP_1MINUS            0x57
#define OP_ULESS             0x58
#define OP_UGREATER          0x59
#define OP_ULESEQ            0x5A
#define OP_UGREATEREQ        0x5B
#define OP_WITHIN            0x5C
#define OP_CELLPLUS          0x5D
#define OP_CELLMINUS         0x5E
#define OP_CELLS             0x5F
#define OP_CFETCH            0x60
#define OP_CSTORE            0x61
#define OP_HFETCH            0x62
#define OP_HSTORE            0x63
#define OP_FETCH             0x64
#define OP_STORE             0x65
#define OP_2FETCH            0x66
#define OP_2STORE            0x67
#define OP_PCFETCH           0x68
#define OP_PCSTORE           0x69
#define OP_PFETCH            0x6A
#define OP_PSTORE            0x6B
#define OP_CMOVE             0x6C
#define OP_CMOVEN            0x6D
#define OP_FILL              0x6E
#define OP_ALIGNED           0x6F
#define OP_COMPARE           0x70
#define OP_SCAN              0x71
#define OP_SKIP              0x72
#define OP_FIND              0x73
#define OP_HFETCHU           0x74
#define OP_HSTOREU           0x75
#define OP_TFETCHU           0x76
#define OP_TSTOREU           0x77
#define OP_FETCHU            0x78
#define OP_STOREU            0x79
#define OP_PLUSSTORE         0x7A
#define OP_DEQ               0x7B
#define OP_DLESS             0x7C
#define OP_DULESS            0x7D

#define OP_0                 0x80
#define OP_1                 0x81
#define OP_2                 0x82
#define OP_3                 0x83
#define OP_4                 0x84
#define OP_1N                0x85

#define OP_TOLOC             0x86
#define OP_TODLOC            0x87
#define OP_TOFLOC            0x88
#define OP_LPPLUS            0x89
#define OP_LOCFETCH          0x8A
#define OP_LOCSTORE          0x8B
#define OP_DLOCFETCH         0x8C
#define OP_DLOCSTORE         0x8D
#define OP_FLOCFETCH         0x8E
#define OP_FLOCSTORE         0x8F

#define OP_FPLUS             0x90
#define OP_FMINUS            0x91
#define OP_FTIMES            0x92
#define OP_FSLASH            0x93
#define OP_FMOD              0x94
#define OP_DTOF              0x95
#define OP_FTOD              0x96
#define OP_FROUND            0x97
#define OP_FTRUNC            0x98
#define OP_FSCALE            0x99
#define OP_STOF              0x9A
#define OP_FTOS              0x9B
#define OP_FABS              0x9C
#define OP_FNEGATE           0x9D
#define OP_FFUNC             0x9F

#define OP_FDROP             0xA0
#define OP_FDUP              0xA1
#define OP_FSWAP             0xA2
#define OP_FOVER             0xA3
#define OP_FROT              0xA4
#define OP_FFETCH            0xA8
#define OP_FSTORE            0xA9
#define OP_SFFETCH           0xAA
#define OP_SFSTORE           0xAB
#define OP_FFETCHU           0xAC
#define OP_FSTOREU           0xAD
#define OP_FISNEG            0xAE
#define OP_FISINF            0xAF

#define OP_F0EQ              0xB0
#define OP_F0NEQ             0xB1
#define OP_F0LESS            0xB2
#define OP_F0GREATER         0xB3
#define OP_F0LESSEQ          0xB4
#define OP_F0GREATEREQ       0xB5
#define OP_FEQ               0xB6
#define OP_FNEQ              0xB7
#define OP_FLESS             0xB8
#define OP_FGREATER          0xB9
#define OP_FLESSEQ           0xBA
#define OP_FGREATEREQ        0xBB
#define OP_FREXP             0xBC
#define OP_FLOOR             0xBD

#define OP_OSCALL            0xC0
#define OP_SPFETCH           0xC1
#define OP_SPSTORE           0xC2
#define OP_RPFETCH           0xC3
#define OP_RPSTORE           0xC4
#define OP_LPFETCH           0xC5
#define OP_LPSTORE           0xC6
#define OP_FPFETCH           0xC7
#define OP_FPSTORE           0xC8
